[package]
name = "rlwekex"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies]
rand = "0.3"
byteorder = "0.5"

[dependencies.stepbymap]
git = "https://github.com/quininer/stepbymap.git"
